#pragma once

#define LENGTH_SHORT_TEXT 20
#define LENGTH_MIDDLE_TEXT 40
#define LENGTH_CONFIG_KEY_VALUE 50
#define LENGTH_THING_NAME 50
#define LENGTH_JSON_BUFFER 500
#define LENGTH_TOPIC 80
#define LENGTH_SENSOR_ACTOR_NAME 50
#define LENGTH_LOGGER_MESSAGE 300
#define LENGTH_STATE 100
#define LENGTH_PAYLOAD 150
